### ISSUE TITLE
Is yellow missing?

### ISSUE THREAD

**Issue by raffaelemancuso** [catppuccin/hyprland#4]
Is it me or yellow is missing across all 4 themes?

**Comment by rubyowo** [comment]
OOPS I DONT KNOW HOW I MISSED THAT
~~would be nice if you'd fix it and send in a PR~~

**Comment by rubyowo** [comment]
Fixed in [ef1385c](https://github.com/catppuccin/hyprland/commit/ef1385ca5982d1368cabf24f0019fead427f402f)
