### ISSUE TITLE
CRLF 'Invalid config line'

### ISSUE THREAD

**Issue by reavessm** [catppuccin/hyprland#8]
After downloading one of the release files and sourcing it in my hyprland conf, I got an error for each blank line in my mocha.conf file.  Long story short, hyprland does not like CRLF.  I had to run `dos2unix <filename>` to fix it.  Maybe this is related to how the themes are templated?  I'm not super familiar with whiskers so I'm not sure

**Comment by rubyowo** [comment]
ah shit. i wrote these on windows so that's the issue

**Comment by rubyowo** [comment]
@reavessm can you recheck with the latest release? it should be LF now.

**Comment by rubyowo** [comment]
actually, scratch that. no more releases
you can just `curl` the file from the repo

**Comment by reavessm** [comment]
Fixed with #12
